name: Node.js CI

on:
    push:
        branches: ["main", "pretext"]
    pull_request:
        branches: ["main", "pretext"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci

            - name: Build
              # `unified-latex-cli` depends on almost all `unified-latex` packages. We build it first
              # so that if it errors, the build will fail.
              run: |
                  npm run build -w packages/unified-latex-cli
                  npm run build -ws --if-present

            - name: Test
              run: npm test

            # This test tests the actual packages that will be distributed
            - name: Test Packages run on ESM and CJS
              run: |
                  npm run test:packages-install
                  npm run test:packages-esm
                  npm run test:packages-cjs
